// react/official/sidemenu/src/pages/List.tsx
import React from 'react';
import { IonHeader, IonToolbar, IonButtons, IonMenuButton, IonTitle, IonContent, IonList, IonItem, IonIcon } from '@ionic/react';
import { ListItem } from '../declarations';

const items: ListItem[] = [
  'flask',
  'wifi',
  'beer',
  'football',
  'basketball',
  'paper-plane',
  'american-football',
  'boat',
  'bluetooth',
  'build'
].map((_item, index, iconList) => ({
  title: `Item ${index}`,
  note: `This is item #${index}`,
  icon: iconList[Math.floor(Math.random() * iconList.length)]
}));

const List: React.SFC = () => (
  <>
  <IonHeader>
    <IonToolbar>
      <IonButtons slot="start">
        <IonMenuButton></IonMenuButton>
      </IonButtons>
      <IonTitle>
        List
      </IonTitle>
    </IonToolbar>
  </IonHeader>

  <IonContent>
    <IonList>
      { items.map((item) => (
      <IonItem>
        <IonIcon name={item.icon} slot="start"></IonIcon>
        {item.title}
        <div className="item-note" slot="end">
          {item.note}
        </div>
      </IonItem>
      ))}
    </IonList>
  </IonContent>
  </>
);

export default List;

// ionic-angular/official/sidemenu/src/pages/list/list.ts
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';

@Component({
  selector: 'page-list',
  templateUrl: 'list.html'
})
export class ListPage {
  selectedItem: any;
  icons: string[];
  items: Array<{ title: string; note: string; icon: string }>;

  constructor(public navCtrl: NavController, public navParams: NavParams) {
    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('item');

    // Let's populate this page with some filler content for funzies
    this.icons = [
      'flask',
      'wifi',
      'beer',
      'football',
      'basketball',
      'paper-plane',
      'american-football',
      'boat',
      'bluetooth',
      'build'
    ];

    this.items = [];
    for (let i = 1; i < 11; i++) {
      this.items.push({
        title: 'Item ' + i,
        note: 'This is item #' + i,
        icon: this.icons[Math.floor(Math.random() * this.icons.length)]
      });
    }
  }

  itemTapped(event, item) {
    // That's right, we're pushing to ourselves!
    this.navCtrl.push(ListPage, {
      item: item
    });
  }
}
