// src/components/ExploreContainer.tsx
import './ExploreContainer.css';

interface ContainerProps {
  name: string;
}

const ExploreContainer: React.FC<ContainerProps> = ({ name }) => {
  return (
    <div id="container">
      <strong>{name}</strong>
      <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
    </div>
  );
};

export default ExploreContainer;

// angular-standalone/official/tabs/src/app/explore-container/explore-container.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-explore-container',
  templateUrl: './explore-container.component.html',
  styleUrls: ['./explore-container.component.scss'],
})
export class ExploreContainerComponent {
  readonly name = input<string>();
}

<div id="container">
  <strong>{{ name() }}</strong>
  <p>
    Explore
    <a
      target="_blank"
      rel="noopener noreferrer"
      href="https://ionicframework.com/docs/components"
      >UI Components</a
    >
  </p>
</div>
