// angular/official/tabs/src/app/explore-container/explore-container.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-explore-container',
  templateUrl: './explore-container.component.html',
  styleUrls: ['./explore-container.component.scss'],
})
export class ExploreContainerComponent {

  @Input() name?: string;

}

<div id="container">
  <strong>{{ name }}</strong>
  <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
  <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/native">Native Functionality</a></p>
  <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionic.io/enterprise-sdk">Enterprise Auth & Security</a></p>
</div>

// react/official/tabs/src/components/ExploreContainer.tsx
import './ExploreContainer.css';

interface ContainerProps {
  name: string;
}

const ExploreContainer: React.FC<ContainerProps> = ({ name }) => {
  return (
    <div className="container">
      <strong>{name}</strong>
      <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
      <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/native">Native Functionality</a></p>
      <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionic.io/enterprise-sdk">Enterprise Auth & Security</a></p>
    </div>
  );
};

export default ExploreContainer;
